### ISSUE TITLE
How to make compatible with vagrant

### ISSUE THREAD

**Issue by nycnewman** [trodemaster/packer-macOS-11#15]
Interested to use this as a means to build a vagrant box for Macos Monterey.  Mainly due to macinbox box now failing due to changes in macOS installer pieces since Big Sur. 

Tried to build with the following observations:

- the buildprerequs.sh appears to pull down pre-release versions by default. I'm assume the change to remove DeveoperSeed is all that's required
- I've tried changing the username/password in macos.pkg.hcl but this appear to be ignored. The documentation seems to suggest a Python utility to recreate the installation packages and scripts but this appears missing from the repo (makepkgs.sh also harcode the file path for the script to include ~/code/... ). Is this available somewhere else?
- Packer appears to hang waiting on SSH to be exposed. Can't find any logs or other means to diagnose why this might be happening. Within guest Remote Login is enabled and a manually attempt to ssh port is successful. Debug option for packer doesn't show any further detalls.

Thoughts appreciated

**Comment by trodemaster** [comment]
Yes if you edit the buildpreques.sh to remove DeveloperSeed it will remove the extended attribute that flags the OS as pre-release. This is also cleared if you run the customize build and specify non pre-release. I'm wanting to replace that whole script at some point but will consider updating it.

You can grab pycreateuserpkg from https://github.com/gregneagle/pycreateuserpkg

SSh login failure is likely due to attempts to change user/pass. Try it without changing anything first. 

As for vagrant. One suggestion I have is to simply add a new user account later in the build process. There is not hard requirement to use the same user the machine image is built by packer with. It's easy to chain in your own scripts using https://github.com/trodemaster/packer-macOS-11#add-your-own-config-script at the end of the customization build.

**Comment by nycnewman** [comment]
Thanks. The odd part is that it ignores the username change and still creates packer and yet SSH still hangs. I found the docs on packer debugging so may get more info. I'll try the above and see how it goes.

**Comment by nycnewman** [comment]
Just a minor follow up but the SSH issue seems to be that Packer times out. I was able to connect from different terminal session but the packer session shows the following logs:

2021/11/17 19:54:33 packer-builder-vmware-iso plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake
2021/11/17 19:54:40 packer-builder-vmware-iso plugin: [INFO] Attempting SSH connection to 192.168.207.134:22...
2021/11/17 19:54:40 packer-builder-vmware-iso plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/11/17 19:54:40 packer-builder-vmware-iso plugin: [DEBUG] handshaking with SSH
2021/11/17 19:55:40 packer-builder-vmware-iso plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake
2021/11/17 19:55:47 packer-builder-vmware-iso plugin: [INFO] Attempting SSH connection to 192.168.207.134:22...
2021/11/17 19:55:47 packer-builder-vmware-iso plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/11/17 19:55:47 packer-builder-vmware-iso plugin: [DEBUG] handshaking with SSH
2021/11/17 19:56:47 packer-builder-vmware-iso plugin: [DEBUG] SSH handshake err: Timeout during SSH handshake
2021/11/17 19:56:54 packer-builder-vmware-iso plugin: [INFO] Attempting SSH connection to 192.168.207.134:22...
2021/11/17 19:56:54 packer-builder-vmware-iso plugin: [DEBUG] reconnecting to TCP connection for SSH
2021/11/17 19:56:54 packer-builder-vmware-iso plugin: [DEBUG] handshaking with SSH

**Comment by trodemaster** [comment]
Looks like a credentials mismatch or some other configuration issue outside of the default state of this template.
