### ISSUE TITLE
Is libvirt provider possible

### ISSUE THREAD

**Issue by dtodt** [trodemaster/packer-macOS-11#17]
Greetings,

I wonder if would be possible to change the provider type from vmware to libvirt.

I'm not used to create boxes, so I'll search for it more from now on.

Thanks.

**Comment by trodemaster** [comment]
There is no libvirt packer provider currently so that would be one challenge. It's possible to boot macOS using QEMU on macOS but the effort involved is large. 

If you are using linux host looking to boot macOS check out these options.
https://github.com/kholia/OSX-KVM
https://github.com/sickcodes/Docker-OSX
